I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 440, in script
    "Nothing really looks different."
  File "game/script.rpy", line 440, in <module>
    "Nothing really looks different."
  File "game/script.rpy", line 235, in increment_show_security
    show_security_level_function(securityLevel)
NameError: global name 'self' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 440, in script
    "Nothing really looks different."
  File "/Users/justicejuraschek/Downloads/renpy-6.99.10-sdk/renpy/ast.py", line 806, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/justicejuraschek/Downloads/renpy-6.99.10-sdk/renpy/python.py", line 1577, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 440, in <module>
    "Nothing really looks different."
  File "game/script.rpy", line 235, in increment_show_security
    show_security_level_function(securityLevel)
NameError: global name 'self' is not defined

Darwin-15.5.0-x86_64-i386-64bit
Ren'Py 6.99.10.1227
Test Experiment 0.0
